/**
 * Vault-based JDex builder. Walks vault files (not `jd-index.yaml`) to
 * rebuild the `## Contents` section of `XX.00` index files at three tiers:
 *
 *   1. Ordinary per-category    — `XX.00` where XX ∉ {00, 10, 20, … 90}.
 *      Lists the category's own folder members.
 *   2. Area-management          — `X0.00` where X ∈ {1..9}.
 *      Consolidates every per-category `## Contents` within the same area.
 *   3. System                   — `00.00`.
 *      Consolidates every per-category `## Contents` across all areas,
 *      grouped by area folder.
 *
 * Descriptions following an em-dash (`[[link]] — note`) are preserved at
 * every tier. The parent tier's local description wins over an inherited
 * one, so users can override at a higher level without having to chase the
 * link to its owning category.
 *
 * Distinct from `render-jdex.ts`, which builds from `jd-index.yaml`. This
 * one is for users whose source-of-truth is the vault structure itself.
 */

import { type App, TFile } from "obsidian";
import { setSection } from "./sections";

/**
 * Per-link annotation we surface in the post-run Notice. Keeps just enough
 * context for the user to find what was preserved (file + link target).
 */
export interface PreservedDescription {
	file: string;
	target: string;
	description: string;
}

export interface ReindexResult {
	preserved: PreservedDescription[];
}

/**
 * Single warning callout used at every tier. Wording is uniform because
 * the preservation guarantee is uniform — bullets regenerate from the
 * vault, italic-paren descriptions persist across runs.
 *
 * We use `*(…)*` (italics in parens) rather than an em-dash separator
 * because obsidian-linter's `remove-space-around-characters` and
 * `remove-link-spacing` rules (with `include-dashes: true`) mangle
 * `[[link]] — desc` into shapes our parser can't reliably recover.
 */
export const CONTENTS_CALLOUT =
	`> [!warning]+ Auto-generated—descriptions preserved\n` +
	`> Regenerated by **Index category** or **Index entire vault**. Bullet links rebuild from the vault on each run; italic-paren descriptions after each link (\`[[…]] *(note)*\`) are preserved.`;

/**
 * Match a bullet line of the form `- [[target(|alias)?]] *(desc)*?`. The
 * target excludes `|` and `]` so a wikilink with an alias splits correctly.
 * The description, if present, sits in `*(…)*` at end-of-line — italics in
 * parens, the same convention used elsewhere in the vault. Greedy `(.+)`
 * backtracks so a description containing nested `*` or `)` still reaches
 * the trailing `)*$` anchor.
 */
const BULLET_RE = /^-\s+\[\[([^\]|]+)(?:\|([^\]]*))?\]\](?:\s+\*\((.+)\)\*)?$/;

/** True for `10`, `20`, … `90` — the area-management JDex prefixes. */
export function isAreaManagement(prefix: string): boolean {
	return prefix.length === 2 && prefix !== "00" && prefix.endsWith("0");
}

/**
 * Read `created:` from a file's YAML frontmatter. Scoped to the leading
 * `---`-delimited region — a `created:` token in the body (prose, code
 * block, embedded YAML example) won't be matched. Returns `fallback`
 * when the file is missing, has no frontmatter, or has no `created:`
 * inside it.
 */
export async function getCreatedDate(app: App, file: TFile, fallback: string): Promise<string> {
	if (!app.vault.getAbstractFileByPath(file.path)) return fallback;
	const existing = await app.vault.read(file);
	if (!existing.startsWith("---\n")) return fallback;
	const close = existing.indexOf("\n---\n", 4);
	if (close === -1) return fallback;
	const fmText = existing.slice(4, close + 1);
	const match = fmText.match(/^created:\s*(.+)$/m);
	return match ? match[1].trim() : fallback;
}

export function buildFrontmatter(
	title: string,
	jdId: string,
	created: string,
	modified: string,
	folderName: string
): string {
	return `---
title: ${title}
jd-id: "${jdId}"
created: ${created}
modified: ${modified}
tags:
  - jd/index
aliases:
  - ${title}
  - ${folderName}
linter-yaml-title-alias: ${title}
---
`;
}

/** Format a single bullet from a TFile, applying optional description. */
function formatBullet(file: TFile, description?: string): string {
	const bn = file.basename;
	const subMatch = bn.match(/^(\d{5,})\.00\s+(.+)$/);
	const link = subMatch ? `[[${bn}|${subMatch[1]} ${subMatch[2]}]]` : `[[${bn}]]`;
	return description ? `- ${link} *(${description})*` : `- ${link}`;
}

export function buildLinks(files: TFile[]): string {
	return files.map((f) => formatBullet(f)).join("\n");
}

/**
 * Returns category-member files, EXCLUDING the index file itself (otherwise
 * the regenerated JDex would contain a wikilink back to itself).
 *
 * Path matching is separator-bounded — a category at `"06 Foo"` doesn't
 * scoop files from a sibling `"06 Foo Long"`. Same scoping invariant as
 * `indexCategory` uses.
 */
export function getCategoryFiles(
	allFiles: TFile[],
	prefix: string,
	folderPath: string,
	excludePath?: string
): TFile[] {
	return allFiles
		.filter((f) => {
			if (excludePath && f.path === excludePath) return false;
			if (!f.basename.startsWith(prefix)) return false;
			if (!f.parent) return false;
			const p = f.parent.path;
			if (p !== folderPath && !p.startsWith(folderPath + "/")) return false;
			return true;
		})
		.sort((a, b) => a.basename.localeCompare(b.basename));
}

/**
 * Parse every bullet line in `content` and return a `target → description`
 * map for those carrying an italic-paren annotation. Used at the
 * area-management and system tiers, where the auto-managed body has nested
 * headings, so we can't section-scope the parse to `## Contents` alone.
 *
 * Also picks up annotations the user wrote in their own sections (e.g.
 * `## IDs`) using the same `*(…)*` convention — those migrate into
 * `## Contents` on the next reindex.
 *
 * The same regex-based filter that ignores callouts and prose also ignores
 * the warning callout we emit, so this is round-trip-safe.
 */
export function parseAllDescriptions(content: string): Map<string, string> {
	const out = new Map<string, string>();
	for (const line of content.split("\n")) {
		const m = line.trim().match(BULLET_RE);
		if (!m) continue;
		const [, target, , desc] = m;
		if (desc) out.set(target, desc);
	}
	return out;
}

/**
 * Apply an overlay description map onto a block of bullet lines. Bullets
 * whose target appears in the overlay get the overlay's description (which
 * trumps any pre-existing one); other bullets pass through verbatim.
 *
 * Returns the rewritten text plus a list of `(target, description)` pairs
 * that were actually applied — caller uses this to surface the preserved
 * set to the user.
 */
export function overlayDescriptions(
	bullets: string,
	overlay: Map<string, string>
): { text: string; applied: Array<[string, string]> } {
	const applied: Array<[string, string]> = [];
	const out = bullets.split("\n").map((line) => {
		const m = line.trim().match(BULLET_RE);
		if (!m) return line;
		const [, target, alias] = m;
		const desc = overlay.get(target);
		if (!desc) return line;
		applied.push([target, desc]);
		const link = alias ? `[[${target}|${alias}]]` : `[[${target}]]`;
		return `- ${link} *(${desc})*`;
	});
	return { text: out.join("\n"), applied };
}

/**
 * Pull just the bullet lines (verbatim) from a `## Contents` section. Used
 * by area-management and system builds to copy each per-category Contents
 * into the consolidated view — descriptions and aliases pass through.
 */
export function extractContentsBullets(content: string): string {
	const lines = content.split("\n");
	const start = lines.findIndex((l) => l.trim() === "## Contents");
	if (start === -1) return "";

	const out: string[] = [];
	for (let i = start + 1; i < lines.length; i++) {
		const t = lines[i].trim();
		if (/^## [^#]/.test(t) || t === "^contents") break;
		if (t.startsWith("- [[")) out.push(lines[i]);
	}
	return out.join("\n");
}

interface CategoryData {
	prefix: string;
	indexFile: TFile;
	folder: NonNullable<TFile["parent"]>;
	areaFolder: NonNullable<TFile["parent"]>["parent"];
	files: TFile[];
}

/**
 * Build the prefix → CategoryData map from a list of vault files. Used by
 * area-management and system builds to discover their sibling categories.
 * Discovery is by `XX.00` filename (where the next char is space, dot, or
 * `+`), matching the same shape ensureCategoryIndexes accepts.
 */
function buildCategoriesMap(allFiles: TFile[]): Map<string, CategoryData> {
	const indexFiles = allFiles.filter((f) => /^\d{2}\.00(?:\s|\.|\+|$)/.test(f.basename));
	const out = new Map<string, CategoryData>();
	for (const indexFile of indexFiles) {
		const m = indexFile.basename.match(/^(\d{2})/);
		if (!m || !indexFile.parent) continue;
		const prefix = m[1];
		// First-write-wins if the same prefix appears in multiple folders
		// (shouldn't happen in a well-formed vault, but don't crash).
		if (out.has(prefix)) continue;
		out.set(prefix, {
			prefix,
			indexFile,
			folder: indexFile.parent,
			areaFolder: indexFile.parent.parent,
			files: getCategoryFiles(allFiles, prefix, indexFile.parent.path, indexFile.path),
		});
	}
	return out;
}

/**
 * Render the `## Contents` body for an ordinary per-category XX.00. Bullets
 * are sorted by file basename so preserved descriptions never affect order
 * — sort is the last step.
 */
export function buildContents(files: TFile[], descriptions: Map<string, string>): string {
	const sorted = [...files].sort((a, b) => a.basename.localeCompare(b.basename));
	const bullets = sorted.map((f) => formatBullet(f, descriptions.get(f.basename))).join("\n");
	return `${CONTENTS_CALLOUT}\n\n${bullets}`;
}

/**
 * Ordinary per-category reindex: list this category's own folder members
 * under `## Contents`, preserving italic-paren descriptions across runs.
 * Other file content (frontmatter, `# Title`, unrelated prose) is left
 * untouched.
 *
 * Description harvest is whole-file (`parseAllDescriptions`) rather than
 * scoped to `## Contents`, so annotations the user wrote in their own
 * sections like `## IDs` migrate into `## Contents` on the next reindex.
 */
async function reindexOrdinary(
	app: App,
	indexFile: TFile,
	allFiles: TFile[]
): Promise<ReindexResult> {
	const prefix = indexFile.basename.match(/^(\d{2})/)![1];
	const folder = indexFile.parent!;
	const catFiles = getCategoryFiles(allFiles, prefix, folder.path, indexFile.path);

	const existing = await app.vault.read(indexFile);
	const descriptions = parseAllDescriptions(existing);
	const body = buildContents(catFiles, descriptions);
	const updated = setSection(existing, "## Contents", body);

	await app.vault.modify(indexFile, updated);

	const catBasenames = new Set(catFiles.map((f) => f.basename));
	const preserved: PreservedDescription[] = [];
	for (const [target, description] of descriptions) {
		if (catBasenames.has(target)) {
			preserved.push({ file: indexFile.path, target, description });
		}
	}
	return { preserved };
}

/**
 * Bullets for one category's contribution to a consolidated view (area or
 * system). For the consolidating file's own category we always rebuild
 * fresh from the vault — its own `## Contents` (if any) is what we're
 * about to overwrite. For sibling categories we copy their `## Contents`
 * verbatim (which already carries their tier-1 preserved descriptions),
 * falling back to a fresh build if the source has none yet, and prepend
 * the sibling's own `XX.00` link so that index file isn't an orphan.
 *
 * (Without the prepend, no upper tier ever links to per-category XX.00
 * files — `getCategoryFiles` excludes self from each cat's listing — so
 * the orphan check flags every JDex.)
 */
async function bulletsForCategory(
	app: App,
	cat: CategoryData,
	selfIndexPath: string
): Promise<string> {
	if (cat.indexFile.path === selfIndexPath) return buildLinks(cat.files);
	const content = await app.vault.read(cat.indexFile);
	const inner = extractContentsBullets(content) || buildLinks(cat.files);
	const indexBullet = `- [[${cat.indexFile.basename}]]`;
	return inner ? `${indexBullet}\n${inner}` : indexBullet;
}

/**
 * Area-management reindex (`X0.00` for X ∈ 1..9). Consolidates every
 * per-category `## Contents` within the same area under `### Folder`
 * sub-headings, including the X0 folder's own files. The consolidating
 * file's own descriptions overlay the inherited ones.
 */
async function reindexAreaManagement(
	app: App,
	indexFile: TFile,
	categories: Map<string, CategoryData>
): Promise<ReindexResult> {
	const selfPrefix = indexFile.basename.match(/^(\d{2})/)![1];
	const self = categories.get(selfPrefix);
	if (!self) return { preserved: [] };
	const areaName = self.areaFolder?.name;

	const areaCats = [...categories.values()]
		.filter((c) => c.areaFolder?.name === areaName)
		.sort((a, b) => a.prefix.localeCompare(b.prefix));

	const existing = await app.vault.read(indexFile);
	const overlay = parseAllDescriptions(existing);
	const preserved: PreservedDescription[] = [];

	let body = `${CONTENTS_CALLOUT}\n\n`;
	for (const cat of areaCats) {
		body += `### ${cat.folder.name}\n\n`;
		const bullets = await bulletsForCategory(app, cat, indexFile.path);
		const result = overlayDescriptions(bullets, overlay);
		for (const [target, description] of result.applied) {
			preserved.push({ file: indexFile.path, target, description });
		}
		body += result.text + "\n\n";
	}

	const updated = setSection(existing, "## Contents", body);
	await app.vault.modify(indexFile, updated);
	return { preserved };
}

/**
 * System reindex (`00.00`). Consolidates every per-category `## Contents`
 * across all areas under `### Area / #### Folder` nested headings. The
 * 00 category's own files appear under their area like any other.
 */
async function reindexSystem(
	app: App,
	indexFile: TFile,
	categories: Map<string, CategoryData>
): Promise<ReindexResult> {
	const areas = new Map<string, CategoryData[]>();
	for (const cat of categories.values()) {
		const areaName = cat.areaFolder?.name ?? "(no area)";
		if (!areas.has(areaName)) areas.set(areaName, []);
		areas.get(areaName)!.push(cat);
	}
	const sortedAreas = [...areas.entries()].sort((a, b) => a[0].localeCompare(b[0]));

	const existing = await app.vault.read(indexFile);
	const overlay = parseAllDescriptions(existing);
	const preserved: PreservedDescription[] = [];

	let body = `${CONTENTS_CALLOUT}\n\n`;
	for (const [areaName, areaCats] of sortedAreas) {
		body += `### ${areaName}\n\n`;
		areaCats.sort((a, b) => a.prefix.localeCompare(b.prefix));
		for (const cat of areaCats) {
			body += `#### ${cat.folder.name}\n\n`;
			const bullets = await bulletsForCategory(app, cat, indexFile.path);
			const result = overlayDescriptions(bullets, overlay);
			for (const [target, description] of result.applied) {
				preserved.push({ file: indexFile.path, target, description });
			}
			body += result.text + "\n\n";
		}
	}

	const updated = setSection(existing, "## Contents", body);
	await app.vault.modify(indexFile, updated);
	return { preserved };
}

/**
 * Single dispatch entry-point used by both `Index category` (one file) and
 * `Index entire vault` (per-category loop). Routes by prefix:
 *
 *   - `00`           → system consolidation across every area
 *   - `10` … `90`    → area-management consolidation within one area
 *   - everything else → ordinary per-category list
 *
 * `Index entire vault` runs categories in tier order so upper tiers consume
 * freshly-rebuilt lower-tier `## Contents`. Calling this on a single file
 * out of order still produces the correct shape for that file, just with
 * potentially stale upstream Contents.
 */
export async function reindexCategory(
	app: App,
	indexFile: TFile,
	allFiles: TFile[]
): Promise<ReindexResult> {
	const prefixMatch = indexFile.basename.match(/^(\d{2})/);
	if (!prefixMatch) return { preserved: [] };
	if (!indexFile.parent) return { preserved: [] };
	const prefix = prefixMatch[1];

	if (prefix === "00") {
		return reindexSystem(app, indexFile, buildCategoriesMap(allFiles));
	}
	if (isAreaManagement(prefix)) {
		return reindexAreaManagement(app, indexFile, buildCategoriesMap(allFiles));
	}
	return reindexOrdinary(app, indexFile, allFiles);
}
