import { App } from "obsidian";
import { JdConfig } from "./jd";
import { VaultScan, scanVault } from "./scan";

const MARKER = "<!-- jd-index:generated -->";

interface Row {
	id: string;
	title: string;
	path: string;
}

/**
 * Render a master JDex index: area -> category -> ids, sorted numerically.
 * Only notes with a valid parsed jd-id are listed. Redirect stubs are skipped.
 */
export function renderIndex(app: App, cfg: JdConfig, scan?: VaultScan): string {
	const s = scan ?? scanVault(app, cfg);

	// area band -> category code -> rows
	const tree = new Map<string, Map<string, Row[]>>();
	const catTitle = new Map<string, string>();
	const areaTitle = new Map<string, string>();

	for (const n of s.notes) {
		const id = n.parsed;
		if (!id || n.isRedirect) continue;
		if (id.kind === "area") {
			areaTitle.set(id.area, n.title);
			continue;
		}
		if (id.kind === "category") {
			catTitle.set(id.category, n.title);
			continue;
		}
		// Category home (standard-zero "AC.00" — the JDex / category folder note):
		// a title source, not a content row. Under filename-canonical a category
		// folder note derives id "AC.00" (kind "id"), so catch it explicitly here
		// rather than via the kind === "category" branch above.
		if (id.kind === "id" && id.raw.endsWith(".00")) {
			catTitle.set(id.category, n.title);
			continue;
		}
		// content / expanded / fractal ids
		const cats = tree.get(id.area) ?? new Map<string, Row[]>();
		const rows = cats.get(id.category) ?? [];
		rows.push({ id: id.raw, title: n.title, path: n.file.path });
		cats.set(id.category, rows);
		tree.set(id.area, cats);
	}

	// Fall back to folder names for area/category titles.
	for (const [area, path] of s.areaFolders)
		if (!areaTitle.has(area)) areaTitle.set(area, path.split("/").pop() ?? area);
	for (const [cat, path] of s.categoryFolders)
		if (!catTitle.has(cat)) catTitle.set(cat, (path.split("/").pop() ?? cat));

	const lines: string[] = [];
	lines.push(MARKER);
	lines.push("# JD index", "");
	lines.push("> Auto-generated by the JD Numbering plugin — do not edit by hand; re-run **JD: Refresh index**.", "");

	const areas = [...tree.keys()].sort();
	let total = 0;
	for (const area of areas) {
		const aName = areaTitle.get(area) ?? area;
		lines.push(`## ${area} ${aName.replace(/^[0-9-]+\s*/, "")}`.trimEnd(), "");
		const cats = tree.get(area)!;
		for (const cat of [...cats.keys()].sort()) {
			const cName = (catTitle.get(cat) ?? "").replace(/^[0-9]+\s*/, "");
			const rows = cats.get(cat)!.sort((a, b) => a.id.localeCompare(b.id));
			total += rows.length;
			lines.push(`### ${cat} ${cName}`.trimEnd(), "");
			for (const r of rows) {
				const clean = r.title.replace(/^[0-9.]+\s*/, "");
				lines.push(`- \`${r.id}\` [[${r.path}|${clean}]]`);
			}
			lines.push("");
		}
	}
	lines.splice(3, 0, `> **${total}** ids across **${areas.length}** areas.`, "");
	return lines.join("\n");
}

export const INDEX_MARKER = MARKER;
