import { App } from "obsidian";
import { JdConfig, isStandardZero } from "./jd";
import { VaultScan, scanVault, expectedFolder } from "./scan";

export type LintLevel = "error" | "warn";

export interface LintFinding {
	level: LintLevel;
	code: string;
	path: string;
	message: string;
}

const RE_COLON = /:/;
const RE_TRAILING_SPACE = / \.md$| $/;

/**
 * Read-only lint of the vault against the JD conventions. Expansion-aware:
 * 5-digit expanded-area / expanded-category ids are valid, not orphans.
 */
export function lintVault(app: App, cfg: JdConfig, scan?: VaultScan): LintFinding[] {
	const s = scan ?? scanVault(app, cfg);
	const findings: LintFinding[] = [];
	const add = (level: LintLevel, code: string, path: string, message: string) =>
		findings.push({ level, code, path, message });

	// Duplicate jd-id (ignoring redirect stubs, which intentionally reuse an id).
	const byId = new Map<string, string[]>();
	for (const n of s.notes) {
		if (!n.frontId || n.isRedirect || !n.parsed) continue;
		const arr = byId.get(n.frontId) ?? [];
		arr.push(n.file.path);
		byId.set(n.frontId, arr);
	}
	for (const [id, paths] of byId) {
		if (paths.length > 1) {
			for (const p of paths)
				add("error", "duplicate-id", p, `jd-id "${id}" is used by ${paths.length} notes`);
		}
	}

	for (const n of s.notes) {
		const path = n.file.path;

		// Malformed jd-id present but unparseable.
		if (n.frontId && !n.parsed) {
			add("error", "malformed-id", path, `jd-id "${n.frontId}" is not a valid JD identifier`);
			continue;
		}

		// Filename that looks like an id but has no / a different frontmatter id.
		const nameLooksLikeId = /^[0-9]/.test(n.file.basename);
		if (nameLooksLikeId && !n.frontId && !n.isFolderNote) {
			add("warn", "missing-frontmatter-id", path, `filename starts with "${n.nameId}" but the note has no jd-id`);
		}

		if (!n.parsed) continue;
		const id = n.parsed;

		// Filename prefix should equal the jd-id (folder notes use area/category form).
		if (!n.isFolderNote && n.nameId !== id.raw) {
			add("warn", "filename-mismatch", path, `filename id "${n.nameId}" != jd-id "${id.raw}"`);
		}

		// Folder placement: the note's category folder should match the id's category.
		const want = expectedFolder(s, id);
		const parent = n.file.parent ? n.file.parent.path : "";
		if (want && parent !== want && !parent.startsWith(want + "/")) {
			add("warn", "folder-mismatch", path, `id "${id.raw}" should live under "${want}", not "${parent}"`);
		} else if (!want && id.kind !== "area") {
			add("warn", "no-category-folder", path, `no folder found for category "${id.category}" (id ${id.raw})`);
		}

		// Naming hygiene.
		if (RE_COLON.test(n.file.name)) {
			add("error", "colon-in-name", path, "filenames must not contain a colon");
		}
		if (RE_TRAILING_SPACE.test(n.file.name)) {
			add("warn", "trailing-space", path, "filename has a trailing space");
		}

		// Standard-zero sanity: a .00–.09 note filed as content is usually a mistake
		// only when it is not a folder/zero note; we simply note it for review.
		if (isStandardZero(id) && n.isRedirect) {
			add("warn", "redirect-on-zero", path, `redirect stub occupies standard-zero ${id.raw}`);
		}
	}

	// Sort: errors first, then by path.
	findings.sort((a, b) =>
		a.level === b.level ? a.path.localeCompare(b.path) : a.level === "error" ? -1 : 1
	);
	return findings;
}

export function renderReport(findings: LintFinding[], cfg: JdConfig): string {
	const errors = findings.filter((f) => f.level === "error");
	const warns = findings.filter((f) => f.level === "warn");
	const lines: string[] = [];
	lines.push("# JD lint report", "");
	lines.push(
		`> Generated by the JD Numbering plugin. **${errors.length}** errors, **${warns.length}** warnings.`,
		`> Expanded areas: \`${cfg.expandedAreas.join(", ") || "none"}\` · expanded categories: \`${cfg.expandedCategories.join(", ") || "none"}\``,
		""
	);
	if (findings.length === 0) {
		lines.push("✅ No issues found.");
		return lines.join("\n");
	}
	const section = (title: string, items: LintFinding[]) => {
		if (items.length === 0) return;
		lines.push(`## ${title}`, "");
		const byCode = new Map<string, LintFinding[]>();
		for (const f of items) {
			const arr = byCode.get(f.code) ?? [];
			arr.push(f);
			byCode.set(f.code, arr);
		}
		for (const [code, arr] of byCode) {
			lines.push(`### \`${code}\` (${arr.length})`, "");
			for (const f of arr) lines.push(`- [[${f.path}|${f.path}]] — ${f.message}`);
			lines.push("");
		}
	};
	section("Errors", errors);
	section("Warnings", warns);
	return lines.join("\n");
}
